#+CATEGORY: paper, congreso, comunicación
#+TAGS: género, web semántica
#+DESCRIPTION: Comunicación para el congreso de Periodisimo, mujer y comunicación
#+TITLE: JPD17, V Jornadas de Periodismo de Datos
#+DATE: <2017-01-16 lun 10:30>
#+AUTHOR: Adolfo Antón Bravo
#+EMAIL: adolfo@medialab-prado.es
#+OPTIONS: todo:nil pri:nil tags:nil ^:nil 

#+OPTIONS: reveal_center:t reveal_progress:t reveal_history:nil reveal_control:t
#+OPTIONS: reveal_mathjax:t reveal_rolling_links:t reveal_keyboard:t reveal_overview:t num:nil
#+OPTIONS: reveal_width:1200 reveal_height:800
#+OPTIONS: toc:nil
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2.5
#+REVEAL_TRANS: linear
#+REVEAL_THEME: sky
#+REVEAL_HLEVEL: 2
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal Introduction.">
#+REVEAL_POSTAMBLE: <p> Creado por adolflow. </p>
#+REVEAL_PLUGINS: (highlight markdown notes)
#+REVEAL_EXTRA_CSS: file:///home/flow/Documentos/software/reveal.js/css/reveal.css
#+REVEAL_ROOT: file:///home/flow/Documentos/software/reveal.js/

* Nombre
V Jornadas de Periodismo de Datos, JPD17, datos abiertos
* Fechas
3-6 Mayo
* Temática
- Datos abiertos
- Datos personales
- Datos ciudadanxs
- ... Periodismo (de datos)
* Abstract/Resumen
Cuando la World Wide Web se nombró como Web 2.0, algunas personas
comenzaron a hablar del *Periodismo 2.0*. Se hacía eco, así, de la
producción de contenidos periodísticos desde medios sociales.

En 2013 comenzamos las Jornadas de Periodismo de Datos y Datos
Abiertos para poner en común conocimiento alrededor de la práctica del
periodismo de datos.

La Web se encuentra en una evolución y cuestionamiento permanente, más
si cabe que la famosa crisis del periodismo. Ya nadie duda, no
obstante, de la trascendencia del medio Web como vehículo natural para
la transmisión de noticias, sean o no producidas ex-profeso para este
medio.

El estado actual de la Web no se ha nombrado recientemente, pero desde
la /Web de Datos/, las instituciones que apuestan por la Web continúan
una senda de profundización en la datización de los contenidos web.

Sin embargo, la exclusividad de la Web como vehículo de transmisión de
contenidos se ve alterado por las aplicaciones cuyo acceso desde
dispositivos móviles conecta a los datos públicos con los privados.

Somos productores de datos, algunos de los cuales se encuentran
disponibles en la Web aunque muchos otros se encuentran tras APIs más
o menos abiertas, con mayor o menor riqueza. En cantidad y calidad no
son ni la punta del iceberg de la producción de datos.

Sea como fuere, aunque consumimos datos discretos, accedemos al
conocimiento a través de la narración de los mismos. He aquí de nuevo
a lxs periodistas, narradores de esta época, tan necesarixs como
siempre, independientemente de que exista una crisis de la industria
del periodismo, de que haya menor o mayor acceso a datos públicos o de
que cuenten con más o menos pericia técnica. El texto ha de seguir
tejiéndose, la realidad ha de seguir produciéndose.

Os invitamos, por tanto, a participar de esta aventura que son las V
Jornadas de Periodismo de Datos. Más allá del periodismo de datos, más
allá del periodismo ciudadano, del 2.0, de las redes sociales, de la
web. Periodismo, al fin y al cabo.
* Call for Papers
Os invitamos a enviar propuestas de:
- Charla
- Demo
- Taller
- Cualquier otra cosa

A través de alguno de los canales de comunicación.

Independientemente del canal, pondremos todas las propuestas como
[[https://github.com/jpdatos/jpd17/issues/][issues]].

** Idioma
Pueden ser en cualquier idioma pero preferiblemente en
Español/Castellano o Inglés.

** Extensión

Máximo 600 palabras

** Deadline/Fecha límite

Antes del 1 de marzo

** Temas
- Antecedentes, perspectiva o estado actual del Periodismo de datos
- Periodismo y redes sociales
- Entornos Web: HTML5, frameworks, CSS, JS
- Entornos multimedia
- Web Semántica, Linked Data
- Alfabetización digital
- Expresiones regulares
- Datos tabulados, datos estructurados, almacenes de datos
- Geodatos
- Datos abiertos
- Casos de éxito
- Uso de software
- Congresos, conferencias, cursos 
- Iniciativas relacionadas
- Narrativas digitales, multimedia y transmedia
- Visualización de datos
- Análisis de datos
- Tipos de datos
- Licencias de los datos y/o de los productos informativos
- Datos personales, privacidad, seguridad en las comunicaciones
- Software y hardware libre y/o abierto
- Drones
- Otros

* Contacto
Puedes escribirnos a datosperiodismo (@) gmail.com

- Adolfo Antón Bravo
- Pilar López López

O bien crear una [[https://github.com/jpdatos/jpd17/issues/new][issue]] o utilizar cualquier canal de comunicación:
** Comunicación
- [[https://github.com/jpdatos][Github jpdatos]]
- Web
- [[https://twitter.com/datosperiodismo][Twitter]]
- [[https://www.facebook.com/Jornadas-de-Periodismo-de-Datos-1541942802770368/?fref=ts][Facebook]]
- [[https://periodismodatos.slack.com/][Slack]]
- Instagram
- [[https://www.flickr.com/photos/146680132@N02/][Flickr]]
- [[https://t.me/joinchat/AAAAAAmWZJYOq4PEGG6kuA][Telegram]]

* Sedes

Repetiremos en Madrid y si todo sigue igual, las posibles sedes serían:
- Asociación de la Prensa de Madrid
- Medialab-Prado
- Fundación Telefónica
* Estudiantes
- Cómo llegar a estudiantes
* Profesionales
- Cómo llegar a profesionales
* Patrocinio
- Necesitamos buscar posibles patrocinios.
* Comunicación
- Redes sociales
- Equipo prensa
- Fotos
- Vídeos
- Periodistas

